# Generated by Django 4.0 on 2022-02-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbloginapp', '0003_rename_fsex_freg_gender_remove_freg_msex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freg',
            name='month',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
