# Generated by Django 4.0 on 2022-02-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbloginapp', '0005_alter_freg_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freg',
            name='month',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
